1. Added install_entr to watch for file changes 2. Added install_md4c to convert md to html 3. Added basic vimrc 4. Replaced vim with nvim as git editor

diff --git a/install_git b/install_git
--- a/install_git
+++ b/install_git
@@ -8,7 +8,7 @@ pacman_pkg="extra/git"
 
 git_mail="ludvig.westerdahl.tech.v1@protonmail.com"
 git_name="ludvig"
-git_editor="vim"
+git_editor="nvim"
 
 handle_repository() {
     arg_repo="${1}"
@@ -43,8 +43,8 @@ inst_is_installed() {
 }
 
 inst_can_install() {
-    if ! is_command vim; then
-        echo "missing vim"
+    if ! is_command nvim; then
+        echo "missing nvim"
         return 1
     fi
 
