Refactored installer and boot

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Docs
+# 1. Sensitive information in install_git
+
 readonly PROG_PATH=${0}
 readonly PROG_DIR=${0%/*}
 readonly FULL_PATH=$(realpath ${PROG_PATH})
@@ -7,31 +10,34 @@ readonly FULL_DIR=$(dirname ${FULL_PATH})
 readonly PROG_NAME=$(basename $0)
 
 readonly INSTALLERS=(
+  "install_less"
+  "install_vim"
   "install_git"
+  "install_basedevel"
+  "install_brave"
+  "install_archwallpaper"
 )
+
 readonly ARG=${1}
 
-declare prog_name=""
+# =====================================================================================
+# ============================== program installer utils ==============================
+# =====================================================================================
 
-source_installer() {
-    prog_name="${1}"
-    source ${prog_name}
-
-}
-
-describe_installer() {
-    echo -e "\033[1m${installer_name}\033[0m - ${installer_description}"
-    echo "| link: ${installer_link}"
-}
-
-pacman_upgrade() {
-    if ! is_command pacman; then
-        echo "pacman does not exist"
-        exit 1
+is_command() {
+    if command -v "${1}" >/dev/null 2>&1; then
+        return 0
+    else
+        return 1
     fi
+}
 
-    sudo pacman --noconfirm -Syu
-    sudo pacman --noconfirm -Fy
+is_pacman_installed() {
+    if pacman -Q "${1}" >/dev/null 2>&1; then
+        return 0
+    else
+        return 1
+    fi
 }
 
 pacman_install() {
@@ -52,14 +58,35 @@ pacman_uninstall() {
     sudo pacman --noconfirm -R ${1}
 }
 
-is_command() {
-    if command -v "${1}" >/dev/null 2>&1; then
-        return 0
-    else
-        return 1
-    fi
+# =============================================================================
+# ============================== installer utils ==============================
+# =============================================================================
+
+describe_installer() {
+    echo -e "\033[1m${installer_name}\033[0m - ${installer_description}"
+    echo "| link: ${installer_link}"
 }
 
+declare prog_inst_name=""
+
+source_installer() {
+    prog_inst_name="${1}"
+    source ${prog_inst_name}
+}
+
+pacman_upgrade() {
+    if ! is_command pacman; then
+        echo "pacman does not exist"
+        exit 1
+    fi
+
+    sudo pacman --noconfirm -Syu
+    sudo pacman --noconfirm -Fy
+}
+
+# =======================================================================
+# ============================== installer ==============================
+# =======================================================================
 
 if [[ "${ARG}" == "install" ]]; then
     pacman_upgrade
@@ -110,13 +137,13 @@ if [[ "${ARG}" == "upgrade" ]]; then
             inst_upgrade
 
             if [[ $? -ne 0 ]]; then
-                echo "failed ${prog_name}"
+                echo "failed ${prog_inst_name}"
                 exit 1
             else
-                echo "success ${prog_name}"
+                echo "success ${prog_inst_name}"
             fi
         else
-            echo "skipping not installed ${prog_name}"
+            echo "skipping not installed ${prog_inst_name}"
         fi
     done
 fi
@@ -133,27 +160,16 @@ if [[ "${ARG}" == "uninstall" ]]; then
             inst_uninstall
 
             if [[ $? -ne 0 ]]; then
-                echo "failed ${prog_name}"
+                echo "failed ${prog_inst_name}"
                 exit 1
             else
-                echo "success ${prog_name}"
+                echo "success ${prog_inst_name}"
             fi
         else
-            echo "skipping not installed ${prog_name}"
+            echo "skipping not installed ${prog_inst_name}"
         fi
     done
 fi
 
 echo "unknown argument ${ARG}"
 exit 1
-
-
-# install_less
-# install_vim
-# install_wallpaper
-# install_base_devel
-# install_brave_binOLD
-
-
-# sensitive information:
-# install_gitold: personal data
