1. Added alias java17spec, slackd 2. Added env function dolphind [DIR] 3. Added nvim-tree keybinding <leader>cd to open a new ghostty window at    that directory. 4. Fixed escaping of \$HOME in alises to expand on use and not inside file

diff --git a/config/bashrc b/config/bashrc
--- a/config/bashrc
+++ b/config/bashrc
@@ -13,34 +13,44 @@ alias slogout="qdbus6 org.kde.Shutdown /Shutdown logout"
 alias ls="ls --color=tty"
 alias grep='grep --color=tty'
 alias top="top -e m -E m -o RES"
-alias wgetmbak="wget --mirror --convert-links --adjust-extension --no-parent --random-wait -e robots=off --reject=\"jpg,jpeg,png,gif,webp,svg,bmp,tiff,ico,mp4,avi,mov,wmv,flv,webm,pdf,zip,rar,iso,exe\""
+alias wgetmbak="wget --mirror --convert-links --adjust-extension --no-parent --random-wait -e robots=off --reject=jpg,jpeg,png,gif,webp,svg,bmp,tiff,ico,mp4,avi,mov,wmv,flv,webm,pdf,zip,rar,iso,exe"
 alias java21doc="braved /usr/share/doc/java21-openjdk/index.html"
+alias java17spec="braved \$HOME/Documents/lwdoc/backup/docs.oracle.com.java17/javase/specs/jls/se17/html/index.html"
 alias jdebugn="java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
 alias jdebugy="java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
 
 #alias braved="rundisown brave"
-alias braved="setsid -f brave >>\"$HOME/.local/share/braved-brave.log\" 2>&1"
-alias postmand="setsid -f postman >>\"$HOME/.local/share/postmand-postman.log\" 2>&1"
-alias vlcd="setsid -f vlc >>\"$HOME/.local/share/vlcd-vlc.log\" 2>&1"
-
+alias braved="setsid -f brave >>\"\$HOME/.local/share/braved-brave.log\" 2>&1"
+alias postmand="setsid -f postman >>\"\$HOME/.local/share/postmand-postman.log\" 2>&1"
+alias vlcd="setsid -f vlc >>\"\$HOME/.local/share/vlcd-vlc.log\" 2>&1"
+alias slackd="setsid -f slack >>\"\$HOME/.local/share/slackd-slack.log\" 2>&1"
 
 # ============================
 # ===   helper functions   ===
 # ============================
 fmtjava() {
-    arg_dir="${1}"
-
-    format_dir="."
-    if [ "${arg_dir}" != "" ]; then
-        format_dir=${arg_dir}
-    fi
+    local arg_dir_file="${1:-.}"
 
     /usr/share/idea/bin/format.sh \
         -s ~/.config/nvim/formatters/intellij-codestyle.xml \
         -m '*.java' \
         -r \
-        "${format_dir}"
+        "${arg_dir_file}"
 }
+
+dolphind() {
+    local arg_dir="${1:-.}"
+
+    if [ ! -d "${arg_dir}" ]; then
+        echo "invalid directory: ${arg_dir}" 1>&2
+        return 1
+    fi
+
+    setsid -f dolphin >> "$HOME/.local/share/dolphind-dolphin.log" 2>&1 "${arg_dir}"
+}
+
+
+
 
 
 # ============================
